HTTPBindPort = 64738
HTTPBindHost = "localhost"
HTTPDebugBindAddres = "localhost"
HTTPDebugPort = 49152
SourceAPIKey = "..."
SourceharedSecret = "..."
CacheHost = "localhost"
CachePort = 6379
CacheKeyExpiry = "30d"
LogFileLocation = "/tmp/songexplorer.log"
MaxTopSimArtists = 10
MaxTopSimTracks = 10
MaxTopArtistTracks = 10