on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/songexplorer:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/songexplorer:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'jesseward/aci-deploy@v2'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/songexplorer:${{ github.sha }}
            ports: 64738:64738
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            secure-environment-variables: lastfmsharedsecret=${{ secrets.LASTFMSHAREDSECRET }} lastfmapikey=${{ secrets.LASTFMAPIKEY }} cachehost=${{ secrets.CACHEHOST }} cachesecret=${{ secrets.CACHESECRET }}
            name: songexplorer
            location: 'east us'
